Something broke jekyll build here, but it works removing spaces.
Not sure what was the reason exactly. Message was not descriptive at all: Error:  undefined method `[]' for nil:NilClass